[package]
name = "token_vis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
charabia = "0.9.2"
html-escape = "0.2.13"
rand = "0.9.0"
serde = "1.0.219"
toml = "0.8.20"
